GET /api/products/45
Host: localhost:9090
Accept: application/json

###
GET /api/products/45
Host: localhost:9090
Accept: application/xml

###

GET /api/products/45
Host: localhost:9090
Accept: text/plain

###

# expecting 1st page
GET /api/products
Host: localhost:9090
Accept: application/json

###

# expecting 3rd page (assuming page size is 10)
GET /api/products?_page=3
Host: localhost:9090
Accept: application/json

###
# expecting 3rd page (assuming page size is 15)
GET /api/products?_page=3&_limit=15
Host: localhost:9090
Accept: application/json

###

GET /api/products/filter?discontinued=true
Host: localhost:9090
Accept: application/json

###

GET /api/products/filter?discontinued=false
Host: localhost:9090
Accept: application/json

###

GET /api/products/filter?min=100&max=1000
Host: localhost:9090
Accept: application/json

###

POST /api/products
Host: localhost:9090
Accept: application/json
Content-Type: application/json

{
    "productName": "Vanilla Milkshake",
    "categoryId": 1,
    "supplierId": 1,
    "quantityPerUnit": "10 boxes x 20 tetrapacks",
    "unitPrice": 2.5,
    "unitsInStock": 20,
    "unitsOnOrder": 0,
    "reorderLevel": 5,
    "discontinued": 0
}

#### update a specific product
PUT /api/products/782
Host: localhost:9090
Accept: application/json
Content-Type: application/json

{
    "productId": 55,
    "productName": "Vanilla Milkshake",
    "categoryId": 1,
    "supplierId": 1,
    "quantityPerUnit": "10 boxes x 20 tetrapacks",
    "unitPrice": 3.5,
    "unitsInStock": 12,
    "unitsOnOrder": 2,
    "reorderLevel": 5,
    "discontinued": 0
}


###

DELETE /api/products/78
Host: localhost:9090
Accept: application/json